### ISSUE TITLE
Add flattened version of all models

### ISSUE THREAD

**Issue by mforets** [JuliaReach/SX.jl#1]
A flattened model contains a single `component`. The idea is to parse this component as a single hybrid system.

Some models are given as a network of components, and before getting into hybrid automata composition, we can do flattening into a single component.

To flatten a model using SpaceEx, do:

```
$ ~/Tools/spaceex_src/sspaceex/Release/sspaceex -g bball_timed.cfg -m bball_timed.xml -o out --output-system-file bball_timed_flattened.xml
```

in my machine:

```
$ ~/Tools/spaceex_src/sspaceex/Release/sspaceex --version
SpaceEx State Space Explorer, v0.9.8e	, compiled Feb 23 2017, 17:42:33, 54-bit float, 65-bit precise float
```

**Comment by mforets** [comment]
@nikos-kekatos  do you know what's going on with the `bball_nondet` example? i get this error:

```
$ ~/Tools/spaceex_exe/spaceex -g bball_nondet.cfg -m bball_nondet.xml -o out --output-system-file bball_nondet_flattened.xml

ERROR: Matrix-vector multiplication with wrong dimensions: Trying to multiply a 2 by 0 matrix with a 5 by 1 vector.
```

**Comment by nikos-kekatos** [comment]
lol I replied in the wrong thread

**Comment by nikos-kekatos** [comment]
have you already constructed the model?

**Comment by nikos-kekatos** [comment]
Note that the flattening process sometimes causes errors when you use the model edit and run it from the web interface. If I recall correctly, there are some symbols that they cannot be parsed, e.g., ~.

**Comment by nikos-kekatos** [comment]
Indeed, if you open this model with MOE the location name cannot be parsed because of the special symbol in line 8
<location id="1" name="always~running">

It does not really play a role but ~ should be deleted/replaced, e.g., <location id="1" name="alwaysrunning">
