### ISSUE TITLE
Error in filtered_oscillator_16 and 32

### ISSUE THREAD

**Issue by mforets** [JuliaReach/SX.jl#2]
```julia
$ sspaceex -g filtered_oscillator_16.cfg -m filtered_oscillator_16.xml -o out --output-system-file filtered_oscillator_16_flattened.xml

ERROR: Failed to parse model file filtered_oscillator_16.xml.
caused by: Could not parse network component osc_w_16th_order.
caused by: Could not parse network component osc_w_16th_order.f8a.
caused by: Cannot map controlled parameter x to uncontrolled parameter osc_w_16th_order.x1.
```

```
$ sspaceex -g filtered_oscillator_32.cfg -m filtered_oscillator_32.xml -o out --output-system-file filtered_oscillator_32_flattened.xml

ERROR: Failed to parse model file filtered_oscillator_32.xml.
caused by: Could not parse network component osc_w_32th_order.
caused by: Could not parse network component osc_w_32th_order.f8d.
caused by: Cannot map controlled parameter x to uncontrolled parameter osc_w_32th_order.z.
```

**Comment by nikos-kekatos** [comment]
I think that there are errors in all of them.

**Comment by nikos-kekatos** [comment]
One thing is with the special symbols used in the notes and another one is with variable names (MOE does not support component_name.variable_name notation, although SpaceEx executable can handle it)

**Comment by mforets** [comment]
> I think that there are errors in all of them.

Alright. Feel free to make a PR with other hybrid models that you may want to try. We have several others in the [reachability benchmarks repo](https://github.com/JuliaReach/ReachabilityBenchmarks/tree/master/models/SLICOT), but these are purely continuous.

**Comment by nikos-kekatos** [comment]
Yes yes, I will do that. For now, we need to check all the flattened models and probably document what are some common errors. It might be necessary to have a postprocessing step so as to be certain that the constructed model works fine..
