### ISSUE TITLE
Initial implementation - flat models

### ISSUE THREAD

**Issue by mforets** [JuliaReach/SX.jl#7]
For the initial implementation i'm  considering two use cases:

(1) purely continuous linear affine models (i.e. no transitions), such as [the motor example](https://github.com/JuliaReach/ReachabilityBenchmarks/blob/master/models/SLICOT/motor/motor.xml), and 
(2) the bouncing ball (there are some variants but i'll stick to [bball/bball_flattened.xml](https://github.com/JuliaReach/SX.jl/blob/master/examples/bball/bball_flattened.xml)).

The screenshot of the SX model of (1) is given below:

![screen shot 2018-04-19 at 13 54 15](https://user-images.githubusercontent.com/12424594/39006366-3b7a4df0-43d9-11e8-9ffb-0ab3969a56ec.png)

The screenshot of the SX model of (2) is given below:

<img width="908" alt="screen shot 2018-04-18 at 11 14 49" src="https://user-images.githubusercontent.com/12424594/38939263-e7b39860-42fd-11e8-9a34-46ab8352382b.png">

In the language of SX (complete description [here](http://spaceex.imag.fr/sites/default/files/spaceex_modeling_language_0.pdf)), components are subsystems (each component is a hybrid system) that can be interconnected (networks). Note that SpaceEx is able to work with networks of components without actually computing the full product automata; this lazy approach is known as "on-the-fly evaluation" of the hybrid automaton (ie. you only compute the states of the full automaton if needed), and it is *needed* for large scale systems. Note that any model with networks of components can be flattened out, however, the resulting automaton may be huge.

To keep it simple models (1) and (2) are flat, that is they have a *single component*. 

Recall that the `HybridSystem` data structure is defined as:

```julia
struct HybridSystem{A, S, R, W} <: AbstractHybridSystem
    automaton::A
    modes::AbstractVector{S}
    resetmaps::AbstractVector{R}
    switchings::AbstractVector{W}
    # Can be used by extensions
    ext::Dict{Symbol, Any}
end
```

The proposal is:

- for the `automaton` take a [LightAutomaton](https://blegat.github.io/HybridSystems.jl/latest/lib/types.html#HybridSystems.LightAutomaton), the number of modes being the number of locations in SX. the transitions are read sequentally and added from the `<transition> ... </transition>` tags.
- the `modes` is a vector where each component is the `flow`. in particular we can use a `System` type. in total generality though we use a list of symbolic expressions (`Expr`). 
- the `resetmaps` are the `<assignment> ... <\assignment>`, list of expressions
- the `switchings`  are the `<guard>... </guard>`, list of inequalities (expressions)

It is easy to parse the XML, i've started to use [EzXML](https://github.com/bicycle1885/EzXML.jl) and it is pretty intuitive. To handle symbolic expressions, we can use Julia's `:(..)` and `parse` that are easy to use. 

However, to transform into a `System` i think we either make a running assumption (eg. that the systems are linear affine), or rely on a CAS like [SymEngine](https://github.com/symengine/symengine). I was able to transform equations but it was unclear to me how to transform inequalities. 

More updates will follow... comments welcome.

**Comment by nikos-kekatos** [comment]
thanks for the summary! I could not understand where invariants are defined. In the modes, only the flows are defined, right? As for the nonlinear dynamics, I think that Christian's suggestion (regarding code modularity) makes complete sense in the long run. However, my impression is that most tools support polynomial nonlinearities but not general nonlinearities (sin, log, etc.). In that case, the PWA-based translation could be adapted accordingly easier.

**Comment by mforets** [comment]
> I know that other tools use the SX format to express nonlinear dynamics.

Yes, see #8. I agree that we shold try to keep that generalization in mind. A strategy is to work in two stages:

(1) from the SX (XML file) model, transform to expressions, `Expr`
(2) from the expressions, create the systems and transform to SymEngine symbolic expressions (`Basic`)

For example: at the level of (1), we have the tuple (`invariants`, `flows`), where each of these is a vector, one for each location (=mode). When we pass to (2), these vectors are transformed into a `modes` which is a vector of `ConstrainedLinearContinuousSystem`, if we work with that assumption of linear afffine systems.

The idea is that (1) will work in general and (2) only given certain assumptions.

> I could not understand where invariants are defined. In the modes, only the flows are defined, right?

we can let each mode wrap the tuple `(invariants, flow)`. note that there are two categories of invariants: those that constraint the states (state constraints) and those that constrain inputs (input constraints). 

but if there is a mix, i would tend to put it as a state constraint, e.g. in `1 <= u1 <= 2 & x1 + u1 >= 0 & `, the first one is an input constraint and the second one is a state constraint, for all admissible values of `u1` in `U = [1, 2]`.
